# global params
device: "cuda"
seed: 42
epochs : 1
limit_steps : -1 # use -1 if you want to train for all steps

# trainer params
trainer:

  # Optimizer Hyperparameters
  learning_rate: 2.25e-05
  beta1: 0.5
  beta2: 0.9

  # Discriminator parameters
  disc_factor: 1.0
  disc_start: 500

  # Loss parameters
  perceptual_loss_factor : 1.0
  perceptual_model: "vgg"
  rec_loss_factor : 1.0

  # Miscellaneous parameters
  save_every: 10
  experiment_dir: "./experiments/cifar10"

# Model Params
model:
  img_channels: 3
  img_size: 256
  latent_channels: 256
  latent_size: 16
  intermediate_channels: [128, 128, 256, 256, 512]
  num_residual_blocks_encoder: 2
  num_residual_blocks_decoder: 3
  dropout: 0
  attention_resolution: [16]
  num_codebook_vectors: 1024

# Data params
dataloader:
  name: "cifar10"
  save_path: "data"
  batch_size: 1
  num_workers: 4
